# Generated by Django 3.2.19 on 2023-06-15 05:20

from django.db import migrations, models
import watchthisshit.models


class Migration(migrations.Migration):

    dependencies = [
        ('watchthisshit', '0002_alter_recommendation_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='watchthisshit.Genre'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='media_type',
            field=models.ForeignKey(default=watchthisshit.models.get_media_type_id, on_delete=models.SET(watchthisshit.models.get_media_type), to='watchthisshit.mediatype'),
        ),
    ]
