# Generated by Django 3.2.19 on 2023-06-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import watchthisshit.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchthisshit', '0003_auto_20230615_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(watchthisshit.models.get_user_if_deleted), related_name='recs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='watchthisshit.profile')),
            ],
        ),
    ]
