# Generated by Django 3.2.19 on 2023-06-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchthisshit', '0005_mediatype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
