# Generated by Django 3.2.19 on 2023-06-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchthisshit', '0006_profile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
    ]
