# Generated by Django 3.2.19 on 2023-06-20 02:32

from django.db import migrations, models
import watchthisshit.models


class Migration(migrations.Migration):

    dependencies = [
        ('watchthisshit', '0007_auto_20230619_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recommendation',
            field=models.ForeignKey(default=watchthisshit.models.get_recommendation_id, on_delete=models.SET(watchthisshit.models.get_recommendation), related_name='comments', to='watchthisshit.recommendation'),
        ),
    ]
